
const arr=[
    {
        id:1,
        name: "Ngo Hieu",
        age: 20,
        images: "/img/i1.jpg",
        // sex: 1,
        address: "bac ninh",
        phone:"098272722",
        hobbies: "game, music",
    },
    {   id:2,
        name: "Manh hien",
        age: 22,
        images: "/img/i2.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:3,
        name: "Van Hang",
        age: 23,
        images: "/img/i3.jpg",
        // sex: 1,
        address: "bac ninh",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:4,
        name: "minh",
        age: 23,
        images: "/img/i4.jpg",
        // sex: 1,
        address: "bac ninh",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:5,
        name: "minh",
        age: 22,
        images: "/img/i5.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:6,
        name: "minh",
        age: 25,
        images: "/img/i6.jpg",
        // sex: 1,
        address: "bac ninh",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:7,
        name: "minh",
        age: 26,
        images: "/img/i7.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:8,
        name: "minh",
        age: 27,
        images: "/img/i8.jpg",
        // sex: 1,
        address: "bac ninh",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:9,
        name: "minh",
        age: 28,
        images: "/img/i9.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:10,
        name: "minh",
        age: 29,
        images: "/img/i10.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:11,
        name: "minh",
        age: 20,
        images: "/img/i11.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:12,
        name: "minh",
        age: 20,
        images: "/img/i12.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:13,
        name: "minh",
        age: 21,
        images: "/img/i13.jpg",
        // sex: 1,
        address: "bac ninh",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:14,
        name: "minh",
        age: 21,
        images: "/img/i14.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },{   id:15,
        name: "minh",
        age: 21,
        images: "/img/i15.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },{   id:16,
        name: "minh",
        age: 21,
        images: "/img/i16.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },{   id:17,
        name: "minh",
        age: 21,
        images: "/img/i17.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:18,
        name: "minh",
        age: 21,
        images: "/img/i18.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:19,
        name: "minh",
        age: 21,
        images: "/img/i19.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    },
    {   id:20,
        name: "minh",
        age: 21,
        images: "/img/i20.jpg",
        // sex: 1,
        address: "ha noi",
        phone:"098272722",
        hobbies: "game, music",

    }









]
localStorage.setItem("keyArr",arr)
console.log(arr)




